"""Two reports for docs/:
  transition_matrix.md : for each arm, every END state -> START state handoff: direct blend time, or the fastest route via a hub, or none.
  collision_matrix.md  : every (A move, B move) pair played as an aligned 1-beat turn in the two-arm sim: closest blade-blade,
                         blade-to-opponent-body and body-to-body distances, with flags for contact to calibrate by hand."""
import sys, json, itertools, numpy as np, mujoco
import arena, ik, tune, chain
from chain import HUBS, path_ok, seg_time, recipe
MOVES = ["ATTACK_HIGH", "ATTACK_LOW_LR", "ATTACK_LOW_RL", "FEINT_HIGH", "FEINT_LEFT", "FEINT_RIGHT", "BLOCK_HIGH", "BLOCK_LEFT", "BLOCK_RIGHT", "BLOCK_MIDDLE"]

def states(arm):
    tune.use_arm(arm); ends = {"REST": tune.REST.copy()}; starts = {"REST": tune.REST.copy()}
    for m in MOVES:
        rec = [np.array(k, float) for k, _ in recipe(m)]; starts[m] = rec[1]; ends[m] = rec[-1]
    for h, q in HUBS.items(): ends[h] = q; starts[h] = q
    return ends, starts

def transition_report():
    out = ["# Transition feasibility (generated by sim/matrices.py)\n", f"Cell = seconds for the handoff from the row's END pose to the column's START pose: plain number = direct blend is safe; `via X n.n` = routed through a hub; `--` = no safe route. Beat window for a connector is ~0.4-0.6 s; longer stretches the beat. Servo blend rate {chain.BLEND_RATE:.0f} deg/s.\n"]
    for arm in ("A", "B"):
        ends, starts = states(arm); cols = list(starts); out.append(f"\n## Arm {arm}\n\n| end \\ start | " + " | ".join(c.replace("ATTACK_", "ATK_").replace("BLOCK_", "BLK_").replace("FEINT_", "FNT_") for c in cols) + " |\n|" + "---|" * (len(cols) + 1))
        for e, qe in ends.items():
            row = []
            for s in cols:
                qs = starts[s]
                if path_ok(qe, qs): row.append(f"{seg_time(qe, qs):.1f}"); continue
                best = None
                for h, qh in HUBS.items():
                    if path_ok(qe, qh) and path_ok(qh, qs):
                        t = seg_time(qe, qh) + seg_time(qh, qs)
                        if best is None or t < best[0]: best = (t, h)
                row.append(f"via {best[1]} {best[0]:.1f}" if best else "--")
            out.append(f"| {e} | " + " | ".join(row) + " |")
    open("../docs/transition_matrix.md", "w").write("\n".join(out) + "\n"); print("wrote docs/transition_matrix.md")

def collision_report():
    spec, m = arena.build(); d = mujoco.MjData(m)
    bodyname = lambda g: mujoco.mj_id2name(m, mujoco.mjtObj.mjOBJ_BODY, m.geom_bodyid[g])
    bladeA = mujoco.mj_name2id(m, mujoco.mjtObj.mjOBJ_GEOM, "A_blade"); bladeB = mujoco.mj_name2id(m, mujoco.mjtObj.mjOBJ_GEOM, "B_blade")
    armA = [g for g in range(m.ngeom) if bodyname(g).startswith("A_") and g != bladeA and m.geom_contype[g]]
    armB = [g for g in range(m.ngeom) if bodyname(g).startswith("B_") and g != bladeB and m.geom_contype[g]]
    ft = np.zeros(6)
    def dist(g1, g2): return float(mujoco.mj_geomDistance(m, d, g1, g2, 0.5, ft))
    T = json.load(open("../arm/motions_tuned.json"))
    def traj(name): M = T[name]; q = np.array(M["q"]); q[:, 4] -= M["roll_offset"]; return np.array(M["t"]), q
    rows = {}; print("simulating 100 pairs...", flush=True)
    for a, b in itertools.product(MOVES, MOVES):
        chain.compile_chain([a], "CHAIN_A", "A", save=True, verbose=False); chain.compile_chain([b], "CHAIN_B", "B", save=True, verbose=False)
        T = json.load(open("../arm/motions_tuned.json")); tA, QA = traj("CHAIN_A"); tB, QB = traj("CHAIN_B")
        arena.set_pose(m, d, QA[0], QB[0]); d.qvel[:] = 0; DT = m.opt.timestep; Tend = max(tA[-1], tB[-1])
        best = {"bb": 9, "Ab": 9, "Ba": 9, "aa": 9}; when = {}
        qi = lambda tt, t, Q: np.array([np.interp(tt, t, Q[:, k]) for k in range(6)])
        for i in range(int(Tend / DT)):
            tt = i * DT; d.ctrl[:6] = arena.q_to_model("A", qi(tt, tA, QA)); d.ctrl[6:] = arena.q_to_model("B", qi(tt, tB, QB)); mujoco.mj_step(m, d)
            if i % 8: continue
            v = {"bb": dist(bladeA, bladeB), "Ab": min(dist(bladeA, g) for g in armB), "Ba": min(dist(bladeB, g) for g in armA), "aa": min(dist(g1, g2) for g1 in armA for g2 in armB)}
            for k in best:
                if v[k] < best[k]: best[k] = v[k]; when[k] = round(tt, 2)
        rows[(a, b)] = (best, when); print(f"  {a:14s} vs {b:14s} blade-blade {best['bb']*100:5.1f}  A blade->B arm {best['Ab']*100:5.1f}  B blade->A arm {best['Ba']*100:5.1f}  arm-arm {best['aa']*100:5.1f} cm", flush=True)
    def flag(best):
        f = []
        if best["aa"] < 0.03: f.append("ARM!")
        if best["Ab"] < 0.015: f.append("A hits B")
        if best["Ba"] < 0.015: f.append("B hits A")
        if best["bb"] < 0.024: f.append("clash")
        return ", ".join(f) or "clear"
    out = ["# Collision watch matrix (generated by sim/matrices.py)\n", "Each cell: the closest approach during an aligned one-beat turn, arm A (SO-100, rows) vs arm B (SO-101, columns), both from their own rest.",
           "Flags: `ARM!` = arm bodies within 3 cm (never allowed); `A hits B` / `B hits A` = a blade within 1.5 cm of the other arm's body (a landing attack: calibrate the end pose by hand so it does not strike hard); `clash` = blades within 2.4 cm (touching). Distances in cm: blade-blade / A-blade-to-B-arm / B-blade-to-A-arm / arm-arm.\n",
           "| A \\ B | " + " | ".join(MOVES) + " |", "|" + "---|" * (len(MOVES) + 1)]
    for a in MOVES:
        out.append(f"| {a} | " + " | ".join(f"**{flag(rows[(a, b)][0])}**<br>{rows[(a, b)][0]['bb']*100:.0f}/{rows[(a, b)][0]['Ab']*100:.0f}/{rows[(a, b)][0]['Ba']*100:.0f}/{rows[(a, b)][0]['aa']*100:.0f}" for b in MOVES) + " |")
    watch = [(a, b, flag(best)) for (a, b), (best, _) in rows.items() if flag(best) != "clear"]
    out.append(f"\n## Pairs to calibrate by hand ({len(watch)})\n"); out += [f"- {a} vs {b}: {f}" for a, b, f in watch]
    open("../docs/collision_matrix.md", "w").write("\n".join(out) + "\n"); json.dump({f"{a}|{b}": {"dist": best, "when": when} for (a, b), (best, when) in rows.items()}, open("out/collision_matrix.json", "w"), indent=1)
    print("wrote docs/collision_matrix.md;", len(watch), "pairs flagged")

if __name__ == "__main__":
    what = sys.argv[1] if len(sys.argv) > 1 else "both"
    if what in ("both", "transitions"): transition_report()
    if what in ("both", "collisions"): collision_report()
